# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'PsychotherapyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PsychotherapyApp
  pod 'StreamChat', '~> 2.4.0'
  pod 'VoxeetUXKit', '~> 1.3.6'
end
